### ISSUE TITLE
Example with more than 3 Cards

### ISSUE THREAD

**Issue by jakobsuckow** [friyiajr/CardShiftAnimation#1]
Hi there,

first of all thanks for your video. It inspired me to integrate your code into my project. Unfortunately, I am running into an issue when dealing with the case of more that 3 cards. For example, when the cards are coming from the backend and you only know the length of the array. Obviously, you cannot create unlimited useSharedValues() for firstPriority, secondPriorty (...nPriority).

So I tried to create an array with priorities rather than initiating each useSharedValue. It works pretty smooth, but it does not seem to update the parent component when I am in the .onEnd() function of the gesture.Pan() domain.

Do you know where the issue could be ?

Keep up the great work :)

`const { height, width } = Dimensions.get("screen");

interface CardContainerProps {
  id: number;
  name: string;
  priorities: SharedValue<number[]>;
  priority: number;
}

const CardContainer: FC<CardContainerProps> = ({ id, name, priority, priorities }) => {

  const BOTTOM_BUFFER = 30;

  const yTranslation = useSharedValue(BOTTOM_BUFFER);

  const gesture = Gesture.Pan()
    .onBegin(({ translationY }) => {
      yTranslation.value = translationY + BOTTOM_BUFFER;
    })

    .onUpdate(({ translationY }) => {
      yTranslation.value = translationY + BOTTOM_BUFFER;
    })
    .onEnd(() => {
      let currentPrioritites = priorities.value;

      console.log("Before", priorities.value);

      const lastItem = currentPrioritites[currentPrioritites.length - 1];

      for (let i = currentPrioritites.length - 1; i > 0; i--) {
        currentPrioritites[i] = currentPrioritites[i - 1];
      }

      currentPrioritites[0] = lastItem;

      priorities.value = currentPrioritites;

      console.log("After", priorities.value);

      yTranslation.value = withTiming(BOTTOM_BUFFER, {
        duration: 400,
      });
    });

  const style = useAnimatedStyle(() => {
    return {
      position: "absolute",
      width: 325,
      height: 200,
      bottom: 100 - priority * 35,
      borderRadius: 20,
      zIndex: priority * 100,
      backgroundColor: "#fff",
      transform: [
        {
          translateY: yTranslation.value,
        },
      ],
    };
  });

  return (
    <GestureDetector gesture={gesture}>
      <FakeCard id={id} style={style} name={name} />
    </GestureDetector>
  );
};

const Projects: React.FC<Props> = (props: Props) => {
  const data = [
    {
      id: 1,
      name: "Name 1 ",
    },
    {
      id: 2,
      name: "Name 2",
    },
    {
      id: 3,
      name: "Name 3",
    },
  ];

  const priorities = useSharedValue<number[]>([0, 1, 2]);

  return (
    <GestureHandlerRootView style={styles.root}>
      <View style={styles.container}>
        {data.map((d, i) => (
          <CardContainer id={d.id} name={d.name} key={i} priorities={priorities} priority={priorities.value[i]} />
        ))}
      </View>
    </GestureHandlerRootView>
  );
};
export default Projects;

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  flatList: {
    marginTop: height * 0.1,
  },
  container: {
    flex: 1,
    alignItems: "center",
  },
});
`

**Comment by friyiajr** [comment]
Hey, thanks for watching 👍. Unfortunately, I am not sure why this isn't working the way you expect `const priorities = useSharedValue<number[]>([0, 1, 2]);`. I think you may need to create an issue with Software Mansion. They would know more then me as to why this behaviour is not what you expect. 

Because this is not a problem with the sample code and its running well I am going to close this issue. But I hope the Software Mansion people have an answer as to why the shared value array isn't working as you'd expect.
